---
# tasks file for sbaerlocher.wsl

- name: 'windows : wsl enable'
  win_dsc:
    resource_name: WindowsOptionalFeature
    Name: Microsoft-Windows-Subsystem-Linux
    Ensure: Enable
  when: wsl_enbale
