---
# tasks file for sbaerlocher.wsl

- name: 'windows : wsl enable'
  win_dsc:
    resource_name: WindowsOptionalFeature
    Name: Microsoft-Windows-Subsystem-Linux
    Ensure: Enable
  when: wsl_enbale

- name: 'windows : create schedule task for wsl'
  win_scheduled_task:
    name: Start WSL Cron
    actions:
    - path: C:\Windows\System32\wsl.exe
      arguments: sudo /etc/init.d/cron start
    triggers:
    - type: daily
      start_boundary: '2019-01-01T02:00:00'
    username: '{{ wsl_users }}'
    author: '{{ wsl_users }}'
    state: present
    enabled: yes
  when: wsl_enbale and wsl_cron
